wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678391896.321061
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      3:
      - 17
      - 23
      - 37
      4: 3.9.16
      5: 0.13.2
      6: 4.17.0
      8:
      - 3
      - 5
